
-- DROP VIEW IF EXISTS MIG_IO_EMPLOYEES_VIEW;

CREATE OR ALTER VIEW MIG_IO_EMPLOYEES_VIEW
AS

SELECT 
CAST(GC.GCT_ID AS NUMERIC(18,0)) AS EMPLOYEEID
,CAST(GC.GCT_ID AS NUMERIC(18,0)) AS NATIONALNUMBER
,ISNULL(employees.CNT_FNAME_AR, '') + ' ' + ISNULL(employees.CNT_LNAME_AR, '') AS FULLNAME
,CASE WHEN CHARINDEX('@', employees.CNT_EMAIL1) <> 0
 THEN LEFT(employees.CNT_EMAIL1, charindex('@', cast(employees.CNT_EMAIL1 AS nvarchar), 0) - 1) 
ELSE  '-'
END AS USERID
,CAST(employees.CurrentStructureGctId AS NUMERIC(18,0)) AS DEPARTMENTID
,professions.PRO_NAME_AR AS JOBTITLE
,CAST(employees.CNT_ACTIVE AS NUMERIC(18,0)) AS ISACTIVE
,NULL AS NOTHAVINGADACCOUNT
,CAST(employees.CNT_RECEIVE_BY_SMS AS NUMERIC(18,0)) AS USE_MOBILE
,employees.CNT_EMAIL1 AS EMP_Email
,employees.CNT_MOBILE AS EMP_Mobile
,NULL AS SPECIALIZATION
,NULL AS QUALIFICATION
,NULL AS DEGREE
,NULL AS EXT
,0 AS IS_HIDDEN
,employees.CNT_ID AS MIGRATED_EMP_ID
,1 AS IS_MIGRATED
,employees.CNT_USERID AS MigratedUserId
,CAST(user_privileges.ESGROUP AS NUMERIC(18,0)) AS PRIVILEGE_ID 
,privileges.NAME AS PRIVELEGE_NAME
,CAST(departments.STC_ID AS NUMERIC(18,0)) AS OLD_SEQ_EMP_DEPARTMENT_ID
,CAST(employees.CNT_ID AS NUMERIC(18,0)) AS OLD_SEQ_EMPLOYEE_ID
,CAST(CNT_STRUCTURE_RECEIVER AS NUMERIC(18,0)) AS EMPLOYEE_STRUCTURE_RECEIVER
,CAST(CNT_PRIVACY_LEVEL_ID AS NUMERIC(18,0)) AS EMPLOYEE_PRIVACY_LEVEL_ID
,CAST(CNT_OTHER_STRUCTURES_DOCUMENT_SEARCH AS NUMERIC(18,0)) AS EMPLOYEE_STRUCTURES_SEARCH
,CAST(CNT_RECEIVE_BY_EMAIL AS NUMERIC(18,0)) AS EMPLOYEE_RECEIVE_EMAIL
,CAST(CNT_RECEIVE_BY_SMS AS NUMERIC(18,0)) AS EMPLOYEE_RECEIVE_SMS
  
FROM [CTS_HRDF].[dbo].[AB_CONTACTS] employees
JOIN [ESSYSTEM_HRDF].[dbo].[ESUSERS] user_privileges 
ON employees.CNT_USERID = user_privileges.ESCOUNT
LEFT JOIN [CTS_HRDF].[dbo].[AB_STRUCTURES] departments
ON employees.CNT_ORG_STC_ID = departments.STC_ID --privleges.ESCOUNT
JOIN [ESSYSTEM_HRDF].[dbo].[ESGROUPS] privileges 
ON user_privileges.ESGROUP = privileges.ESCOUNT
LEFT JOIN [CTS_HRDF].[dbo].AB_GLOBAL_CONTACTS GC  ON employees.CNT_ID = GC.CNT_ID
LEFT OUTER JOIN [CTS_HRDF].[dbo].PROFESSIONS professions  ON employees.PRO_ID = professions.PRO_ID



