
-- DROP VIEW IF EXISTS MIG_IO_RELATIONS_VIEW;

CREATE OR ALTER VIEW MIG_IO_RELATIONS_VIEW
AS

SELECT  

ISNULL(CAST(doc1.DOC_SEQUENCE AS NUMERIC),-1) AS CORRESPONDENCENUMBER,
ISNULL(CAST(SUBSTRING(ISNULL(CAST(FORMAT(CAST(doc1.DOC_REGISTERDATE AS DATE), 'yyyyMMdd', 'ar-SA') AS NVARCHAR),'-1'),0,5) AS NUMERIC),-1) AS HIJRICYEAR,
CASE 
	WHEN doc1.DOC_CATEGORY = 1
		THEN 1
	WHEN doc1.DOC_CATEGORY = 5
		THEN 2
	WHEN doc1.DOC_CATEGORY = 7
		THEN 3
	WHEN doc1.DOC_CATEGORY = 13   ---- Decisions - Internal Memo
		THEN 44
	WHEN doc1.DOC_CATEGORY = 11   ---- Circulars - Internal Broadcast
		THEN 55
ELSE   -1
END AS TYPEID,


ISNULL(CAST(lnkdoc2.DOC_SEQUENCE AS NUMERIC),-1) AS RELATEDTONUMBER,
ISNULL(CAST(SUBSTRING(ISNULL(CAST(FORMAT(CAST(lnkdoc2.DOC_REGISTERDATE AS DATE), 'yyyyMMdd', 'ar-SA') AS NVARCHAR),'-1'),0,5) AS NUMERIC),-1) AS RELATEDTOHIJRICYEAR,
CASE 
	WHEN lnkdoc2.DOC_CATEGORY = 1
		THEN 1
	WHEN lnkdoc2.DOC_CATEGORY = 5
		THEN 2
	WHEN lnkdoc2.DOC_CATEGORY = 7
		THEN 3
	WHEN lnkdoc2.DOC_CATEGORY = 13   ---- Decisions - Internal Memo
		THEN 44
	WHEN lnkdoc2.DOC_CATEGORY = 11   ---- Circulars - Internal Broadcast
		THEN 55
ELSE   -1
END AS RELATEDTOTYPEID,
1 AS RELATIONTYPEID,
-1 AS RECORDNUMBER,
ISNULL(emps.FULLNAME,'not_found_user') AS RELATEDBY,
ISNULL(CAST (FORMAT ( Cast(doc1.DOC_REGISTERDATE AS Date), 'dd/MM/yyyy', 'ar-SA' ) AS NVARCHAR),'-1') AS RELATIONDATE,
1 AS IS_MIGRATED,

emps.EMPLOYEEID AS EMPLOYEEID,
GC.CNT_LNAME AS LinkedBy,
GC.GCT_ID AS GCT_ID,
liks.LNK_ID, liks.LNK_DOCLINKED, lnkdoc2.DOC_REFERENCE AS LNKD_REFERENCE, 
lnkdoc2.DOC_SUBJECT AS LNKD_SUBJECT, doc1.DOC_SUBJECT, liks.LNK_DOC, doc1.DOC_DOCUMENTNUMBER AS ManualReference, 
doc1.DOC_REFERENCE, doc1.DOC_REGISTERDATE, doc1.DOC_STATUS, doc1.DOC_SUMMARY

FROM  
CTS_HRDF.dbo.CTS_LINKS liks 
INNER JOIN CTS_HRDF.dbo.CTS_DOCUMENTS AS doc1 ON doc1.DOC_ID = liks.LNK_DOCLINKED 
INNER JOIN CTS_HRDF.dbo.CTS_DOCUMENTS AS lnkdoc2 ON lnkdoc2.DOC_ID = liks.LNK_DOC
LEFT JOIN MOAMALAT.dbo.IO_EMPLOYEES emps on liks.UserID = emps.MigratedUserId
LEFT JOIN MOAMALAT.dbo.IO_DEPARTMENTS depts on doc1.DOC_REGISTERBY_STRUCTURE = depts.DEPARTMENTID
LEFT JOIN CTS_HRDF.dbo.V_Contacts_GlobalContacts GC ON liks.UserID = GC.CNT_USERID
WHERE doc1.DOC_STATUS_ID <> 46
 --order by DOC_REGISTERDATE desc