
-- DROP VIEW IF EXISTS MIG_IO_DEPARTMENTS_VIEW;

CREATE OR ALTER VIEW MIG_IO_DEPARTMENTS_VIEW
AS

SELECT 
CAST(GC.GCT_ID AS NUMERIC(18,0)) AS DEPARTMENTID
,departments.STC_NAME_AR AS DEPARTMENTNAME
,1 AS MANAGERID
,1 AS REPRESENTATIVEID
,CAST(GCC.GCT_ID AS NUMERIC(18,0)) AS PARENTDEPARTMENTID
,1 AS DEPARTMENTLEVEL
,1 AS CANACCESSSYSTEM
,departments.STC_CODE AS DEPARTMENTCODE
,1 AS ISACTIVE
,NULL AS ALIASNAME
,0 AS ISPUBLICRECEIVER
,1 AS sectorNumber
,-1 AS departmentType
,-1 AS divisionNumber
,-1 AS LocationID
,0 AS ISMINISTEROFFICE
,0 AS IS_HIDDEN
,-1 AS GeneralAdministration
,1 AS IS_MIGRATED
,CAST(GC.STC_ID AS NUMERIC(18,0)) AS OLD_SEQ_DEPARTMENT_ID

FROM [CTS_HRDF].[dbo].AB_STRUCTURES departments 
JOIN [CTS_HRDF].[dbo].AB_GLOBAL_CONTACTS GC ON departments.STC_ID = GC.STC_ID
JOIN [CTS_HRDF].[dbo].AB_GLOBAL_CONTACTS GCC ON departments.STC_PARENT_ID = GCC.STC_ID
WHERE departments.MYORGANIZATION = 1