
-- DROP VIEW IF EXISTS MIG_IO_EXTERNALUNITS_VIEW;

CREATE OR ALTER VIEW MIG_IO_EXTERNALUNITS_VIEW
AS

SELECT 
	GC.GCT_ID AS EXTERNALUNITID, 
	structures.STC_NAME_AR AS EXTERNALUNITDESC,
	0 AS EXTERNALUNITTYPE,
	structures.STC_CODE AS MOCODE,
	1 AS ISACTIVE,
	0 AS YESSERUNITID,
	0 AS YESSER_AVAILABLE,
	0 AS category,
	REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(SUBSTRING (structures.STC_NAME_AR,1,899), 'أ', 'ا'), 'إ', 'ا'), 'ة', 'ه'), 'ي', 'ى'), 'ئ', 'ا'), 'ت', 'ه') AS EXTERNALUNITDESCSEARCH,
	1 AS IS_MIGRATED

FROM       
	[CTS_HRDF].[dbo].AB_GLOBAL_CONTACTS AS GC INNER JOIN
	[CTS_HRDF].[dbo].AB_STRUCTURES structures ON GC.STC_ID = structures.STC_ID
where structures.MYORGANIZATION <> 1