
-- DROP VIEW IF EXISTS MIG_IO_INTERNAL_VIEW;

CREATE OR ALTER VIEW MIG_IO_INTERNAL_VIEW
AS

SELECT
	ISNULL(CAST(documents.DOC_SEQUENCE AS NUMERIC),-1) AS CORRESPONDENCENUMBER,
	--ISNULL(CAST(SUBSTRING(ISNULL(CAST(FORMAT(CAST(documents.DOC_REGISTERDATE AS DATE), 'yyyyMMdd', 'ar-SA') AS NVARCHAR),'-1'),0,5) AS NUMERIC),-1) AS HIJRICYEAR,
	CASE 
		WHEN CAST(FORMAT(CAST(documents.DOC_REGISTERDATE AS DATE), 'yyyyMMdd', 'ar-SA') AS NVARCHAR) IS NULL 
		THEN
			CAST(SUBSTRING(ISNULL( CAST(FORMAT(CAST(RIGHT(CAST([DOC_REFERENCE] AS nvarchar), 
			LEN(CAST([DOC_REFERENCE] AS nvarchar)) - 
			CHARINDEX('-', CAST([DOC_REFERENCE] AS varchar)) ) AS DATE),'yyyyMMdd', 'ar-SA') AS NVARCHAR),
			RIGHT(CAST([DOC_REFERENCE] AS nvarchar), LEN(CAST([DOC_REFERENCE] AS nvarchar)) - 
			CHARINDEX('-', CAST([DOC_REFERENCE] AS varchar)) )),0,5) AS NUMERIC) 
		ELSE
			ISNULL(CAST(SUBSTRING(ISNULL(CAST(FORMAT(CAST(documents.DOC_REGISTERDATE AS DATE), 'yyyyMMdd', 'ar-SA') 
			AS NVARCHAR),'-1'),0,5) AS NUMERIC),-1)
		END
	AS HIJRICYEAR,
	CASE 
		WHEN CAST(FORMAT(CAST(documents.DOC_REGISTERDATE AS DATE), 'yyyyMMdd', 'ar-SA' ) AS NUMERIC) IS NULL
		THEN 
			CONCAT(CAST(SUBSTRING(ISNULL( CAST(FORMAT(CAST(RIGHT(CAST([DOC_REFERENCE] AS nvarchar), 
			LEN(CAST([DOC_REFERENCE] AS nvarchar)) - 
			CHARINDEX('-', CAST([DOC_REFERENCE] AS varchar)) ) AS DATE),'yyyyMMdd', 'ar-SA') AS NVARCHAR),
			RIGHT(CAST([DOC_REFERENCE] AS nvarchar), LEN(CAST([DOC_REFERENCE] AS nvarchar)) - 
			CHARINDEX('-', CAST([DOC_REFERENCE] AS varchar)) )),0,5) AS NUMERIC),'0101')
		ELSE
			CAST(FORMAT(CAST(documents.DOC_REGISTERDATE AS DATE), 'yyyyMMdd', 'ar-SA' ) AS NUMERIC)
		END 
	AS CORRESPONDENCEDATE,
	--ISNULL(CAST(FORMAT(CAST(documents.DOC_REGISTERDATE AS DATE), 'yyyyMMdd', 'ar-SA' ) AS NUMERIC),'-1') AS CORRESPONDENCEDATE,
	2 AS CORRESPONDENCETYPEID, --- THERE IS NO LKP FROM OLD SYSTEM, SO THE DEFAULT VALUE IS 2 = خطاب
	ISNULL(CAST(documents.DOC_CLASSIFICATION AS NUMERIC),1) AS CORRESPONDENCECATEGORYID, --- ( CTS_CLASSIFICATION LKP ) 1:if document type NULL set value to 1 = ---
	documents.DOC_SUBJECT AS CORRESPONDENCESUBJECT,
	summary.SUMMARY AS REMARKS,
	ISNULL(documents.DOC_SUMMARY, '0') AS CORRESPONDENCEATTACHMENTS,
	ISNULL(emps.USERID,'not_found_user') AS SENTBY,
	ISNULL(depts.DEPARTMENTID,9999) AS SENTBYDEPARTMENTID,
	CASE 
		WHEN CAST(documents.DOC_TEXT2 AS NUMERIC) = 1
			THEN 0
		WHEN CAST(documents.DOC_TEXT2 AS NUMERIC) = 2
			THEN 1
		WHEN CAST(documents.DOC_TEXT2 AS NUMERIC) = 3
			THEN 2
		ELSE documents.DOC_TEXT2
	END CONFIDENTIALITYID,
	CASE 
		WHEN documents.DOC_STATUS_ID = 46  ---- DRAFT
			THEN 0
		ELSE 1
	END AS WF_LAUNCHED,
	0 AS ISEXPORTED,
	NULL AS MINISTEROFFICENUMBER,
	-1 AS lastForwardingDate,
	REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(SUBSTRING (documents.DOC_SUBJECT,1,899), 'أ', 'ا'), 'إ', 'ا'), 'ة', 'ه'), 'ي', 'ى'), 'ئ', 'ا'), 'ت', 'ه') AS SearchableSubject,
	NULL AS SYSTEM_OWNER,
	documents.DOC_REGISTERDATE AS CREATIONDATE,
	1 AS IS_MIGRATED,
	documents.DOC_ID AS OLD_DOC_ID,
	documents.DOC_REFERENCE AS REFERENCE

FROM CTS_HRDF.dbo.CTS_DOCUMENTS AS documents
LEFT JOIN CTS_HRDF.dbo.CTS_DOCS_SUMMARY summary on documents.DOC_ID = summary.DOCID
LEFT JOIN MOAMALAT.dbo.IO_EMPLOYEES emps on documents.DOC_REGISTEREDBY = emps.EMPLOYEEID
LEFT JOIN MOAMALAT.dbo.IO_DEPARTMENTS depts on documents.DOC_REGISTERBY_STRUCTURE = depts.DEPARTMENTID
WHERE documents.DOC_CATEGORY = 7
AND documents.DOC_SEQUENCE IS NOT NULL

