
-- DROP VIEW IF EXISTS MIG_IO_FORWARDINGSHISTORY_VIEW;

CREATE OR ALTER VIEW MIG_IO_FORWARDINGSHISTORY_VIEW
AS

SELECT DISTINCT
		trans.TSF_ID AS FORWARDINGID,
		ISNULL(CAST(documents.DOC_SEQUENCE AS NUMERIC),-1) AS CORRESPONDENCENUMBER,
		ISNULL(CAST(SUBSTRING(ISNULL(CAST(FORMAT(CAST(documents.DOC_REGISTERDATE AS DATE), 'yyyyMMdd', 'ar-SA') AS NVARCHAR),'-1'),0,5) AS NUMERIC),-1) AS HIJRICYEAR,
		CASE 
			WHEN documents.DOC_CATEGORY = 1
				THEN 1
			WHEN documents.DOC_CATEGORY = 5
				THEN 2
			WHEN documents.DOC_CATEGORY = 7
				THEN 3
			WHEN documents.DOC_CATEGORY = 13
				THEN 44
			WHEN documents.DOC_CATEGORY = 11
				THEN 55
		ELSE   -1
		END AS TYPEID,
		CASE 
			WHEN ISNULL(trans.PriorityId, 0) = 0
				THEN 0
			WHEN trans.PriorityId = 1
				THEN 0
			WHEN trans.PriorityId = 2
				THEN 0
			WHEN trans.PriorityId = 3
				THEN 1
			WHEN trans.PriorityId = 4
				THEN 2
			WHEN trans.PriorityId = 138
				THEN 3
		ELSE   0
		END AS URGENCYLEVEL,
		CASE 
			WHEN ISNULL(documents.DOC_IMPORTANCE, 0) = 0
				THEN 0
			WHEN documents.DOC_IMPORTANCE = 1
				THEN 0
			ELSE 1
		END AS IMPORTANCELEVEL,
		NULL AS REMINDER, 
		NULL AS DEADLINE, 
		ISNULL(CAST(FORMAT(CAST(trans.TSF_DATE AS DATETIME), 'dd/MM/yyyy hh:mm:ss', 'ar-SA') AS VARCHAR(20)), '01/01/1400 12:00:00') AS FORWARDINGTIME,
		trans.TSF_PURPOSE_AR AS INSTRUCTIONS, 
		NULL AS MINISTER_FORWARDINGID, 
		0 AS ISIGNORED, 
		NULL AS IGNOREDBY, 
		ISNULL(CAST(FORMAT(CAST(trans.TSF_DATE AS Date), 'yyyyMMdd', 'ar-SA') AS NUMERIC), '14000101') AS FORWARDINGDATE, 
		'' AS ATTACHMENTS, 
		NULL AS DEADLINE_backup, 
		documents.DOC_SUBJECT AS H_CORRESPONDENCESUBJECT, 
		ISNULL(emps.USERID,'not_found_user') AS H_SENTBY,
		NULL AS H_MINISTEROFFICENUMBER, 
		NULL AS IS_SIGN_REQUEST, 
		NULL AS VIP_ATTACHMENT, 
		NULL AS VIP_PRESENTED_TYPE, 
		NULL AS LETTER_ATTACHMENT, 
		0 AS IS_CREATED, 
		1 AS IS_MIGRATED,
		trans.TSF_ID AS OLD_DOC_ID
		--,*

		FROM
		CTS_HRDF.dbo.CTS_TRANSFERS trans 
		LEFT OUTER JOIN CTS_HRDF.dbo.CTS_DOCUMENTS documents ON trans.DOC_ID = documents.DOC_ID
		LEFT JOIN MOAMALAT.dbo.IO_EMPLOYEES emps on trans.TSF_FROM = emps.EMPLOYEEID
		-- WHERE TSF_PURPOSE_ID <> 29   ---- CC
		
		
--LEFT JOIN MOAMALAT.dbo.IO_DEPARTMENTS depts on documents.DOC_REGISTERBY_STRUCTURE = depts.DEPARTMENTID
--WHERE trans.PriorityId = 138 --trans.DOC_ID = 363361


--select max(FORWARDINGID) from MOAMALAT.dbo.IO_FORWARDINGSHISTORY where HIJRICYEAR = 1441 
--select * from MOAMALAT.dbo.IO_FORWARDINGDETAILS where FORWARDINGID = 388521 

--select * from CTS_TRANSFERS where TSF_ID = 388521   ---- 341039
--select * from IO_FORWARDINGSHISTORY