 --DROP VIEW IF EXISTS MIG_IO_INCOMING_VIEW;

CREATE OR ALTER VIEW MIG_IO_INCOMING_VIEW
AS

SELECT
	ISNULL(CAST(documents.DOC_SEQUENCE AS NUMERIC),-1) AS CORRESPONDENCENUMBER,
	ISNULL(CAST(SUBSTRING(ISNULL(CAST(FORMAT(CAST(documents.DOC_REGISTERDATE AS DATE), 'yyyyMMdd', 'ar-SA') AS NVARCHAR),'-1'),0,5) AS NUMERIC),-1) AS HIJRICYEAR,--DOC_DOCUMENTDATE,
	ISNULL(CAST(FORMAT(CAST(documents.DOC_REGISTERDATE AS DATE), 'yyyyMMdd', 'ar-SA' ) AS NUMERIC),'-1') AS CORRESPONDENCEDATE,
	2 AS CORRESPONDENCETYPEID, --- THERE IS NO LKP FROM OLD SYSTEM, SO THE DEFAULT VALUE IS 2 = خطاب
	ISNULL(CAST(documents.DOC_CLASSIFICATION AS NUMERIC),1) AS CORRESPONDENCECATEGORYID, --- ( CTS_CLASSIFICATION LKP ) 1:if document type NULL set value to 1 = ---
	documents.DOC_SUBJECT AS CORRESPONDENCESUBJECT,
	summary.SUMMARY AS REMARKS,
	documents.DOC_DOCUMENTNUMBER AS EXTERNALNUMBER,
	0 AS EXTERNALDATE, ---- Not Found from old sys
	ISNULL(CAST(externalUnitDept.EXTERNALUNITID AS NUMERIC),99999) AS CORRESPONDENCESOURCEID,
	1 AS RECEIVEMODEID, 
	1 AS ISARCHIVED,
	ISNULL(documents.DOC_SUMMARY, '0') AS CORRESPONDENCEATTACHMENTS,
	--documents.DOC_REGISTEREDBY AS RECEIVEDBY,
	--documents.DOC_REGISTERBY_STRUCTURE AS RECEIVEDBYDEPARTMENTID,
	ISNULL(emps.USERID,'not_found_user') AS RECEIVEDBY,
	ISNULL(depts.DEPARTMENTID,9999) AS RECEIVEDBYDEPARTMENTID,
	CASE 
		WHEN documents.DOC_STATUS_ID = 46  ---- DRAFT
			THEN 0
		ELSE 1
	END AS WF_LAUNCHED,
	CASE 
		WHEN CAST(documents.DOC_TEXT2 AS NUMERIC) = 1
			THEN 0
		WHEN CAST(documents.DOC_TEXT2 AS NUMERIC) = 2
			THEN 1
		WHEN CAST(documents.DOC_TEXT2 AS NUMERIC) = 3
			THEN 2
		ELSE documents.DOC_TEXT2
	END AS CONFIDENTIALITYID,
	'' AS SENDERDETAILS,
	0 AS ISEXPORTED,
	NULL AS MINISTEROFFICENUMBER,
	1 AS CORRESPONDENCESOURCETYPE,
	--CAST(ownerDepts.DEPARTMENTID AS NUMERIC) AS OWNERDEPARTMENTID,
	CASE
		WHEN (ISNUMERIC(documents.DOC_RECIPIENT) <> 1 AND documents.DOC_RECIPIENT IS NULL)
			THEN 9999
		WHEN (ISNUMERIC(documents.DOC_RECIPIENT) <> 1 AND documents.DOC_RECIPIENT IS NOT NULL)
			THEN SUBSTRING(documents.DOC_RECIPIENT,0,CHARINDEX('/',documents.DOC_RECIPIENT,0))
		ELSE
			documents.DOC_RECIPIENT
	END AS OWNERDEPARTMENTID,
	NULL AS RECORDNUMBER,
	REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(SUBSTRING (documents.DOC_SUBJECT,1,899), 'أ', 'ا'), 'إ', 'ا'), 'ة', 'ه'), 'ي', 'ى'), 'ئ', 'ا'), 'ت', 'ه') AS SearchableSubject,
	'' AS SearchableSENDERDETAILS,
	'' AS CIVIL_RECORD,
	'' AS COMMERCE_RECORD,
	'' AS MOBILE_NUMBER,
	'' AS EMAIL,
	NULL AS SYSTEM_OWNER,
	documents.DOC_REGISTERDATE AS CREATIONDATE,
	NULL AS IS_ENCRYPTED,
	NULL AS DecisionDate,
	NULL AS DecisionNumber,
	1 AS IS_MIGRATED,
	documents.DOC_ID AS OLD_DOC_ID,
	documents.DOC_REFERENCE AS REFERENCE

FROM CTS_HRDF.dbo.CTS_DOCUMENTS AS documents
LEFT JOIN CTS_HRDF.dbo.CTS_DOCS_SUMMARY summary on documents.DOC_ID = summary.DOCID
LEFT JOIN MOAMALAT.dbo.IO_EMPLOYEES emps on documents.DOC_REGISTEREDBY = emps.EMPLOYEEID
LEFT JOIN MOAMALAT.dbo.IO_DEPARTMENTS depts on documents.DOC_REGISTERBY_STRUCTURE = depts.DEPARTMENTID
--LEFT JOIN MOAMALAT.dbo.IO_DEPARTMENTS ownerDepts on CAST(documents.DOC_RECIPIENT AS NUMERIC) = ownerDepts.DEPARTMENTID
LEFT JOIN MOAMALAT.dbo.IO_EXTERNALUNITS externalUnitDept on CAST(documents.DOC_SENDER AS NUMERIC) = externalUnitDept.EXTERNALUNITID
WHERE documents.DOC_CATEGORY = 1
AND documents.DOC_SEQUENCE IS NOT NULL



--select DOC_DOCUMENTNUMBER,DOC_SENDER,SUBSTRING(DOC_RECIPIENT,0,CHARINDEX('/',DOC_RECIPIENT,0)) AS firstPart 
--,DOC_RECIPIENT,DOC_REGISTERBY_STRUCTURE,* from CTS_DOCUMENTS documents
--where documents.DOC_CATEGORY = 1
--AND (ISNUMERIC(DOC_RECIPIENT) <> 1 AND DOC_RECIPIENT is not null)
--order by documents.DOC_ID desc

--DECLARE @s VARCHAR(50)= '125/130/148/43/156/160/167'

--SELECT SUBSTRING('125/130/148/43/156/160/167',0,CHARINDEX('/','125/130/148/43/156/160/167',0)) AS firstPart,
--    SUBSTRING(@s,CHARINDEX('/',@s,0)+1,LEN(@s)) AS secondPart
