
UPDATE IO_INTERNAL 

SET CORRESPONDENCEATTACHMENTS = interV.CORRESPONDENCEATTACHMENTS 

FROM IO_INTERNAL inter
JOIN MIG_IO_INTERNAL_VIEW interV 
ON inter.CORRESPONDENCENUMBER = interV.CORRESPONDENCENUMBER
AND inter.HIJRICYEAR = interV.HIJRICYEAR

WHERE inter.CORRESPONDENCENUMBER = interV.CORRESPONDENCENUMBER
AND inter.HIJRICYEAR = interV.HIJRICYEAR


-----------------------------------------------------------------------------------------------------------



UPDATE IO_INCOMING 

SET OLD_DOC_ID = incomV.OLD_DOC_ID 

FROM IO_INCOMING incom
JOIN MIG_IO_INCOMING_VIEW incomV 
ON incom.CORRESPONDENCENUMBER = incomV.CORRESPONDENCENUMBER
AND incom.HIJRICYEAR = incomV.HIJRICYEAR

WHERE incom.CORRESPONDENCENUMBER = incomV.CORRESPONDENCENUMBER
AND incom.HIJRICYEAR = incomV.HIJRICYEAR



-----------------------------------------------------------------------------------------------------------


UPDATE IO_INCOMING 

SET CORRESPONDENCESOURCEID = incomV.CORRESPONDENCESOURCEID 

FROM IO_INCOMING incom
JOIN MIG_IO_INCOMING_VIEW incomV 
ON incom.CORRESPONDENCENUMBER = incomV.CORRESPONDENCENUMBER
AND incom.HIJRICYEAR = incomV.HIJRICYEAR

WHERE incom.CORRESPONDENCENUMBER = incomV.CORRESPONDENCENUMBER
AND incom.HIJRICYEAR = incomV.HIJRICYEAR


-----------------------------------------------------------------------------------------------------------


UPDATE IO_OUTGOINGDESTINATIONS

SET OLD_DOC_ID = outDest.OLD_DOC_ID 

FROM IO_OUTGOINGDESTINATIONS outDest
JOIN MIG_IO_OUTGOING_DESTINATIONS_VIEW outDestV 
ON outDestV.CORRESPONDENCENUMBER = outDest.CORRESPONDENCENUMBER
AND outDestV.HIJRICYEAR = outDest.HIJRICYEAR
AND outDestV.CORRESPONDENCEDESTINATIONID = outDest.CORRESPONDENCEDESTINATIONID

WHERE outDest.CORRESPONDENCENUMBER = outDestV.CORRESPONDENCENUMBER
AND outDest.HIJRICYEAR = outDestV.HIJRICYEAR   
AND outDestV.CORRESPONDENCEDESTINATIONID = outDest.CORRESPONDENCEDESTINATIONID
AND outDest.IS_MIGRATED = 1


-----------------------------------------------------------------------------------------------------------


UPDATE IO_EMPLOYEES 

SET MigratedUserId = empV.MigratedUserId 

FROM IO_EMPLOYEES emps 
JOIN MIG_IO_EMPLOYEES_VIEW empV
ON emps.EMPLOYEEID = empV.EMPLOYEEID
WHERE emps.EMPLOYEEID = empV.EMPLOYEEID


-----------------------------------------------------------------------------------------------------------


UPDATE IO_FORWARDINGSHISTORY 

SET FORWARDINGTIME = fhV.FORWARDINGTIME 

FROM IO_FORWARDINGSHISTORY fh
JOIN MIG_IO_FORWARDINGSHISTORY_VIEW fhV 
ON fh.CORRESPONDENCENUMBER = fhV.CORRESPONDENCENUMBER
AND fh.HIJRICYEAR = fhV.HIJRICYEAR
AND fh.FORWARDINGID = fhV.FORWARDINGID
AND fh.TYPEID = fhV.TYPEID

WHERE fh.CORRESPONDENCENUMBER = fhV.CORRESPONDENCENUMBER
AND fh.HIJRICYEAR = fhV.HIJRICYEAR
AND fh.FORWARDINGID = fhV.FORWARDINGID
AND fh.TYPEID = fhV.TYPEID

