
-- DROP VIEW IF EXISTS MIG_IO_DEPARTMENTQUEUES_VIEW;

CREATE OR ALTER VIEW [MIG_IO_DEPARTMENTQUEUES_VIEW]
AS

SELECT 
	DEPARTMENTID AS DEPARTMENTID,
	DEPARTMENTNAME AS DEPARTMENTNAME,
	DEPARTMENTNAME AS DEPARTMENTNAMEEN,
	'#' + CAST(DEPARTMENTID AS varchar(20)) AS QUEUENAME,
	'RolesPublicInbox' AS QUEUESHORTNAME,
	CAST(FORMAT(Cast(GETDATE() AS DATE), 'yyyyMMdd', 'ar-SA') AS NUMERIC) QUEUEHIJRICREATEDATE,
	DEPARTMENTNAME AS DEPARTMENTQueueNAMEAR,
	DEPARTMENTNAME AS DEPARTMENTQueueNAMEEN,
	'RolesPublicInbox' AS WORKQUEUES,
	'Moamalat Application Spaces' AS applicationSpaceName,
	DEPARTMENTNAME AS roleName_English,
	DEPARTMENTNAME AS roleName_Arabic,
	1 AS IS_MIGRATED
FROM IO_DEPARTMENTS
WHERE ISACTIVE = 1