
CREATE OR ALTER VIEW [dbo].[MIG_PI_USERS_DEPARTMENTS_VIEW]

AS

SELECT DISTINCT
EMPS.USERID AS Username,
DEPTS.DEPARTMENTID AS DEPARTMENTID
FROM 
IO_EMPLOYEES EMPS INNER JOIN IO_DEPARTMENTS DEPTS ON EMPS.DEPARTMENTID = DEPTS.DEPARTMENTID
WHERE EMPS.ISACTIVE = 1 AND EMPS.ISACTIVE = 1