

select count(*),CORRESPONDENCENUMBER,HIJRICYEAR from MIG_IO_INTERNAL_VIEW
where WF_LAUNCHED = 1
and HIJRICYEAR = 1443
group by CORRESPONDENCENUMBER,HIJRICYEAR
having count(*) > 1

select * from MIG_IO_INTERNAL_VIEW 
where CORRESPONDENCENUMBER = 2838 and HIJRICYEAR = 1443


select * from CTS_HRDF.dbo.CTS_DOCUMENTS
where DOC_ID in (338818,352637)

select * from CTS_HRDF.dbo.CTS_TRANSFERS where DOC_ID in (338818,352637)

select count(*),CORRESPONDENCENUMBER,HIJRICYEAR from MIG_IO_OUTGOING_VIEW
where WF_LAUNCHED = 1
and HIJRICYEAR = 1444
group by CORRESPONDENCENUMBER,HIJRICYEAR
having count(*) > 1



select --a.Items,
a.CORRESPONDENCENUMBER,a.HIJRICYEAR,a.CorrespondenceType from(
SELECT 
--doc_recipients.Items,
ISNULL(CAST(documents.DOC_SEQUENCE AS NUMERIC),-1) AS CORRESPONDENCENUMBER,
ISNULL(CAST(SUBSTRING(ISNULL(CAST(FORMAT(CAST(documents.DOC_REGISTERDATE AS DATE), 'yyyyMMdd', 'ar-SA') AS NVARCHAR),'-1'),0,5) AS NUMERIC),-1) AS HIJRICYEAR,
CASE 
	WHEN documents.DOC_CATEGORY = 1
		THEN 1
	WHEN documents.DOC_CATEGORY = 5
		THEN 2
	WHEN documents.DOC_CATEGORY = 7
		THEN 3
	WHEN documents.DOC_CATEGORY = 13   ---- Decisions - Internal Memo
		THEN 44
	WHEN documents.DOC_CATEGORY = 11   ---- Circulars - Internal Broadcast
		THEN 55
ELSE   -1
END AS CorrespondenceType

from CTS_HRDF.dbo.CTS_DOCUMENTS documents
--CROSS APPLY dbo.fun_Split(DOC_RECIPIENT, '/') as doc_recipients
--where 
--DOC_STATUS_ID <> 46
--AND 
--(ISNUMERIC(DOC_RECIPIENT) <> 1 AND DOC_RECIPIENT is not null)
--and DOC_ID = 142662
  --order by documents.DOC_ID desc
  ) as a
where a.CorrespondenceType not in (1,2,3,44,55)





;WITH IO_INTERNAL_TABLE AS(
SELECT --DOC_REFERENCE,
ISNULL(CAST(documents.DOC_SEQUENCE AS NUMERIC),-1) AS CORRESPONDENCENUMBER,
ISNULL(CAST(SUBSTRING(ISNULL(CAST(FORMAT(CAST(documents.DOC_REGISTERDATE AS DATE), 'yyyyMMdd', 'ar-SA') AS NVARCHAR),'-1'),0,5) AS NUMERIC),-1) AS HIJRICYEAR,--DOC_DOCUMENTDATE,
ISNULL(CAST(FORMAT(CAST(documents.DOC_REGISTERDATE AS DATE), 'yyyyMMdd', 'ar-SA' ) AS NUMERIC),'-1') AS CORRESPONDENCEDATE,
2 AS CORRESPONDENCETYPEID, --- THERE IS NO LKP FROM OLD SYSTEM, SO THE DEFAULT VALUE IS 2 = خطاب
ISNULL(CAST(documents.DOC_CLASSIFICATION AS NUMERIC),1) AS CORRESPONDENCECATEGORYID, --- ( CTS_CLASSIFICATION LKP ) 1:if document type NULL set value to 1 = ---
documents.DOC_SUBJECT AS CORRESPONDENCESUBJECT,
summary.SUMMARY AS REMARKS,
NULL AS CORRESPONDENCEATTACHMENTS,
ISNULL(emps.USERID,'not_found_user') AS SENTBY,
ISNULL(depts.DEPARTMENTID,9999) AS SENTBYDEPARTMENTID,
CASE 
	WHEN CAST(documents.DOC_TEXT2 AS NUMERIC) = 1
		THEN 0
	WHEN CAST(documents.DOC_TEXT2 AS NUMERIC) = 2
		THEN 1
	WHEN CAST(documents.DOC_TEXT2 AS NUMERIC) = 3
		THEN 2
	ELSE documents.DOC_TEXT2
END CONFIDENTIALITYID,
CASE 
	WHEN documents.DOC_STATUS_ID = 46  ---- DRAFT
		THEN 0
	ELSE 1
END AS WF_LAUNCHED,
0 AS ISEXPORTED,
NULL AS MINISTEROFFICENUMBER,
-1 AS lastForwardingDate,
REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(SUBSTRING (documents.DOC_SUBJECT,1,899), 'أ', 'ا'), 'إ', 'ا'), 'ة', 'ه'), 'ي', 'ى'), 'ئ', 'ا'), 'ت', 'ه') AS SearchableSubject,
NULL AS SYSTEM_OWNER,
documents.DOC_REGISTERDATE AS CREATIONDATE,
1 AS IS_MIGRATED
-- ,* 
FROM CTS_HRDF.dbo.CTS_DOCUMENTS AS documents
LEFT JOIN CTS_HRDF.dbo.CTS_DOCS_SUMMARY summary on documents.DOC_ID = summary.DOCID
LEFT JOIN MOAMALAT.dbo.IO_EMPLOYEES emps on documents.DOC_REGISTEREDBY = emps.EMPLOYEEID
LEFT JOIN MOAMALAT.dbo.IO_DEPARTMENTS depts on documents.DOC_REGISTERBY_STRUCTURE = depts.DEPARTMENTID
WHERE documents.DOC_CATEGORY = 7 --- INTERNAL CORRESPONDENCES
AND documents.DOC_SEQUENCE IS NOT NULL
)
SELECT * FROM IO_INTERNAL_TABLE 
WHERE 
--IO_INTERNAL_TABLE.CORRESPONDENCENUMBER IS NOT NULL
--AND 
IO_INTERNAL_TABLE.HIJRICYEAR = 1444
--ORDER BY IO_INTERNAL_TABLE.CORRESPONDENCENUMBER desc
ORDER BY IO_INTERNAL_TABLE.CORRESPONDENCEDATE desc
;

----- 79,433
--select * from CTS_TRANSFERS
--where DOC_ID = 362801



SELECT  new_depts.DEPARTMENTID,new_depts.DEPARTMENTCODE,new_depts.DEPARTMENTNAME,'-',
old_depts.DEPARTMENTID,old_depts.DEPARTMENTCODE,old_depts.DEPARTMENTNAME -- RIGHT(DEPARTMENTCODE,(LEN(DEPARTMENTCODE) - PATINDEX('%[^0]%',DEPARTMENTCODE)) + 1),*
from IO_DEPARTMENTS old_depts 
join moamalat.dbo.MIG_IO_DEPARTMENTS_VIEW new_depts
on RIGHT(old_depts.DEPARTMENTCODE,(LEN(old_depts.DEPARTMENTCODE) - PATINDEX('%[^0]%',old_depts.DEPARTMENTCODE)) + 1) = new_depts.DEPARTMENTID
