
--DELETE FROM IO_EMPLOYEESCONFIGS
--WHERE EMPLOYEEID NOT IN (10000010,10000011,22039,99999)

PRINT 'Inserting into IO_EMPLOYEESCONFIGS'
PRINT GETDATE()


BEGIN TRY

	INSERT INTO [dbo].[IO_EMPLOYEESCONFIGS]
			   ([EMPLOYEEID]
			   ,[ENABLEDOPTIONSMASK]
			   ,[MOSORTORDER]
			   ,[ACSORTORDER]
			   ,[FORWARDINGTOLIST]
			   ,[PRIVILEGE_VERSION]
			   ,[ENABLEDOPTIONSMASKVIP])
    
	SELECT EMPLOYEEID,1,1,1,1,1,1 FROM IO_EMPLOYEES
	WHERE EMPLOYEEID NOT IN (10000010,10000011)

BEGIN CATCH
        SELECT  
            ERROR_NUMBER() AS ErrorNumber  
            ,ERROR_SEVERITY() AS ErrorSeverity  
            ,ERROR_STATE() AS ErrorState  
            ,ERROR_PROCEDURE() AS ErrorProcedure  
            ,ERROR_LINE() AS ErrorLine  
            ,ERROR_MESSAGE() AS ErrorMessage;  
END CATCH



