

--DELETE IO_CORRESPONDENCECATEGORIES WHERE CORRESPONDENCECATEGORYID <> 1

PRINT 'Inserting into IO_CORRESPONDENCECATEGORIES'
PRINT GETDATE()


BEGIN TRY


	INSERT INTO [dbo].[IO_CORRESPONDENCECATEGORIES]
			   ([CORRESPONDENCECATEGORYID],[CORRESPONDENCECATEGORYDESC])
		 
	SELECT ID,CLAS_NAME_AR FROM CTS_HRDF.DBO.CTS_CLASSIFICATION

END TRY  
BEGIN CATCH

        SELECT  
            ERROR_NUMBER() AS ErrorNumber  
            ,ERROR_SEVERITY() AS ErrorSeverity  
            ,ERROR_STATE() AS ErrorState  
            ,ERROR_PROCEDURE() AS ErrorProcedure  
            ,ERROR_LINE() AS ErrorLine  
            ,ERROR_MESSAGE() AS ErrorMessage;  
END CATCH



