UPDATE [MOAMALAT].[dbo].[IO_EXTERNALUNITS] 
SET [EXTERNALUNITDESCSEARCH] = 
REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(ISNULL([EXTERNALUNITDESCSEARCH], ' '), 'أ', 'ا'), 'إ', 'ا'), 'ة', 'ه'), 'ي', 'ى'), 'ئ', 'ا'), 'ت', 'ه');