INSERT INTO [dbo].[IO_FULL_SEARCH_FORWARDINGS]
           ([FULLSEARCH_ID]
           ,[USERID]
           ,[DEPARTMENTID]
           ,[FORWARDINGDETAILID])
			
SELECT 
FULLSEARCH_ID ,
IO_FORWARDINGDETAILS.PARTICIPANTUSERID,
IO_FORWARDINGDETAILS.PARTICIPANTDEPTID,
IO_FORWARDINGDETAILS.FORWARDINGDETAILID

FROM IO_FORWARDINGSHISTORY 
INNER JOIN IO_FORWARDINGDETAILS ON IO_FORWARDINGSHISTORY.FORWARDINGID=IO_FORWARDINGDETAILS.FORWARDINGID
INNER JOIN IO_FULL_SEARCH_CORRESPONDENCE ON IO_FORWARDINGSHISTORY.CORRESPONDENCENUMBER=IO_FULL_SEARCH_CORRESPONDENCE.CORRESPONDENCENUMBER
AND IO_FORWARDINGSHISTORY.HIJRICYEAR=IO_FULL_SEARCH_CORRESPONDENCE.HIJRICYEAR
AND IO_FORWARDINGSHISTORY.TYPEID=IO_FULL_SEARCH_CORRESPONDENCE.CORRESPONDENCETYPE
AND IO_FORWARDINGSHISTORY.ISIGNORED=0;
			
