
BEGIN TRY

	INSERT INTO [dbo].[IO_FULL_SEARCH_CORRESPONDENCE]
           ([CORRESPONDENCENUMBER]
           ,[HIJRICYEAR]
           ,[CORRESPONDENCETYPE]
           ,[MINISTEROFFICENUMBER]
           ,[CREATIONTYPE]
           ,[CORRESPONDENCEDATE]
           ,[CORRESPONDENCESUBJECT]
           ,[EXTERNALNUMBER]
           ,[EXTERNALUNITID]
           ,[EXTERNALUNITDESC]
           ,[CREATOR]
           ,[CONFIDENTIALITYID]
           ,[WF_LAUNCHED]
           ,[CORRESPONDENCESUBJECTSEARCH]
           ,[EXTERNALUNITDESCSEARCH]
		   ,CREATORDEPARTMENT
		   ,CORRESPONDENCENUMBERSEARCHABLE
		   ,SEARCHALLFILEDS
		   )
	 SELECT
           CORRESPONDENCENUMBER
           ,HIJRICYEAR
           ,1
           ,MINISTEROFFICENUMBER
           ,CASE WHEN MINISTEROFFICENUMBER IS NULL THEN 1 ELSE  2 END
           ,CORRESPONDENCEDATE
           ,CORRESPONDENCESUBJECT
           ,EXTERNALNUMBER
           ,EXTERNALUNITID
           ,EXTERNALUNITDESC
           ,RECEIVEDBY
           ,CONFIDENTIALITYID
           ,WF_LAUNCHED
           ,REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CORRESPONDENCESUBJECT, 'أ', 'ا'), 'إ', 'ا'), 'ة', 'ه'), 'ي', 'ى'), 'ئ', 'ا'), 'ت', 'ه')
           ,REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(IO_EXTERNALUNITS.EXTERNALUNITDESC, 'أ', 'ا'), 'إ', 'ا'), 'ة', 'ه'), 'ي', 'ى'), 'ئ', 'ا'), 'ت', 'ه')
		   ,RECEIVEDBYDEPARTMENTID
		   ,CASE WHEN MINISTEROFFICENUMBER IS NULL THEN CAST(CORRESPONDENCENUMBER  AS VARCHAR) ELSE  CAST(MINISTEROFFICENUMBER  AS VARCHAR) END
		   --,replace(replace(replace(replace(replace(replace(SUBSTRING(CORRESPONDENCESUBJECT, 1, 899), 'أ', 'ا'), 'إ', 'ا'), 'ة', 'ه'), 'ي', 'ى'), 'ئ', 'ا'), 'ت', 'ه')
		   ,CONCAT(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(SUBSTRING(CORRESPONDENCESUBJECT, 1, 899), 'أ', 'ا'), 'إ', 'ا'), 'ة', 'ه'), 'ي', 'ى'), 'ئ', 'ا'), 'ت', 'ه'), ' ', CORRESPONDENCENUMBER)
		   FROM IO_INCOMING 
		   INNER JOIN IO_EXTERNALUNITS ON CORRESPONDENCESOURCEID=IO_EXTERNALUNITS.EXTERNALUNITID
		   --where HIJRICYEAR >= 1440
		   ORDER BY HIJRICYEAR,CORRESPONDENCENUMBER
		   
	END TRY
	
    BEGIN CATCH
        SELECT  
            ERROR_NUMBER() AS ErrorNumber  
            ,ERROR_SEVERITY() AS ErrorSeverity  
            ,ERROR_STATE() AS ErrorState  
            ,ERROR_PROCEDURE() AS ErrorProcedure  
            ,ERROR_LINE() AS ErrorLine  
            ,ERROR_MESSAGE() AS ErrorMessage;  
    END CATCH