
BEGIN TRY

  INSERT INTO [dbo].[IO_FULL_SEARCH_CORRESPONDENCE]
           ([CORRESPONDENCENUMBER]
           ,[HIJRICYEAR]
           ,[CORRESPONDENCETYPE]
           ,[MINISTEROFFICENUMBER]
           ,[CREATIONTYPE]
           ,[CORRESPONDENCEDATE]
           ,[CORRESPONDENCESUBJECT]
           ,[EXTERNALNUMBER]
           ,[EXTERNALUNITID]
           ,[EXTERNALUNITDESC]
           ,[CREATOR]
           ,[CONFIDENTIALITYID]
           ,[WF_LAUNCHED]
           ,[CORRESPONDENCESUBJECTSEARCH]
           ,[EXTERNALUNITDESCSEARCH]
		   ,CREATORDEPARTMENT
		   ,CORRESPONDENCENUMBERSEARCHABLE
		   ,SEARCHALLFILEDS
		   )
	 SELECT
           IO_OUTGOING.CORRESPONDENCENUMBER
           ,IO_OUTGOING.HIJRICYEAR
           ,2
           ,MINISTEROFFICENUMBER
           ,CASE WHEN MINISTEROFFICENUMBER IS NULL THEN 1 ELSE  2 END
           ,CORRESPONDENCEDATE
           ,CORRESPONDENCESUBJECT
           ,NULL
           ,EXTERNALUNITID
           ,EXTERNALUNITDESC
           ,SENTBY
           ,CONFIDENTIALITYID
           ,WF_LAUNCHED
           ,REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CORRESPONDENCESUBJECT, 'أ', 'ا'), 'إ', 'ا'), 'ة', 'ه'), 'ي', 'ى'), 'ئ', 'ا'), 'ت', 'ه')
           ,REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(IO_EXTERNALUNITS.EXTERNALUNITDESC, 'أ', 'ا'), 'إ', 'ا'), 'ة', 'ه'), 'ي', 'ى'), 'ئ', 'ا'), 'ت', 'ه')
		   ,SENTBYDEPARTMENTID
		   ,CASE WHEN MINISTEROFFICENUMBER IS NULL THEN CAST(IO_OUTGOING.CORRESPONDENCENUMBER  AS VARCHAR) ELSE  CAST(MINISTEROFFICENUMBER  AS VARCHAR) END
		   --,replace(replace(replace(replace(replace(replace(SUBSTRING(CORRESPONDENCESUBJECT, 1, 899), 'أ', 'ا'), 'إ', 'ا'), 'ة', 'ه'), 'ي', 'ى'), 'ئ', 'ا'), 'ت', 'ه')
		   ,CONCAT(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(SUBSTRING(CORRESPONDENCESUBJECT, 1, 899), 'أ', 'ا'), 'إ', 'ا'), 'ة', 'ه'), 'ي', 'ى'), 'ئ', 'ا'), 'ت', 'ه'), ' ', IO_OUTGOING.CORRESPONDENCENUMBER)
		   FROM IO_OUTGOING
		   INNER JOIN IO_OUTGOINGDESTINATIONS ON  IO_OUTGOING.CORRESPONDENCENUMBER=IO_OUTGOINGDESTINATIONS.CORRESPONDENCENUMBER AND IO_OUTGOING.HIJRICYEAR=IO_OUTGOINGDESTINATIONS.HIJRICYEAR AND IO_OUTGOINGDESTINATIONS.LETTERTYPEID=1
		   INNER JOIN IO_EXTERNALUNITS ON IO_OUTGOINGDESTINATIONS.CORRESPONDENCEDESTINATIONID=IO_EXTERNALUNITS.EXTERNALUNITID
		   --where IO_OUTGOING.HIJRICYEAR >= 1440
		   ORDER BY IO_OUTGOING.HIJRICYEAR,IO_OUTGOING.CORRESPONDENCENUMBER
		   
	END TRY
	
    BEGIN CATCH
        SELECT  
            ERROR_NUMBER() AS ErrorNumber  
            ,ERROR_SEVERITY() AS ErrorSeverity  
            ,ERROR_STATE() AS ErrorState  
            ,ERROR_PROCEDURE() AS ErrorProcedure  
            ,ERROR_LINE() AS ErrorLine  
            ,ERROR_MESSAGE() AS ErrorMessage;  
    END CATCH